#' Links those forms of violence to the conflict-month dataset that have to be linked by location
#'
#' @param gedintersection GED events spatially intersected with conflict zones. Passed on from the intersect function
#' @param basedata Conflict-month dataset, generated by the acdtomonthly function and passed through
#' @param gedtrack A version of GED that tracks for each event how it was linked
#' @param divide_deaths User choice for events that fall into multiple conflict zones: use full casualties in each or divide deaths between the conflicts?
#'
#' @return The basedata with violence added, and a version of GED that tracks for each event how it was linked
#' @keywords internal
#'
#' @import dplyr
#' @import tidyr
#' @import stringr
#'
#' @examples
#' \dontrun{
#'   spatiallink(gedintersection,basedata,gedtrack,divide_deaths = FALSE)
#' }
spatiallink <- function(
    gedintersection,
    basedata,
    gedtrack,
    divide_deaths = FALSE
    ) {

  # Function to divide deaths
  divide_deaths_func <- function(data) {
    data <- data %>%
      group_by(idsplit, side_a_new_id, side_b_new_id) %>%
      mutate(best_divided = best / n(),
             best = best_divided) %>%
      ungroup() %>%
      select(-best_divided)
    if ("deaths_civilians" %in% colnames(data)) {
      data <- data %>%
        group_by(idsplit, side_a_new_id, side_b_new_id) %>%
        mutate(deaths_civilians_divided = deaths_civilians / n(),
               deaths_civilians = deaths_civilians_divided) %>%
        ungroup() %>%
        select(-deaths_civilians_divided)
    }
    return(data)
  }

  # Subfunction: zone_wrv, zone_osv, zone_nsv
  process_wrv <- function(divide_deaths) {
    baserelevantepimonths <- basedata %>% select(conflict_epi_id, month_year) %>% mutate(activeepisodes = 1)
    local_gedinter <- left_join(gedintersection, baserelevantepimonths, by = c("z_conf_id" = "conflict_epi_id", "final_date" = "month_year"))
    local_gedinter <- local_gedinter %>% filter(activeepisodes == 1)
    if (divide_deaths) local_gedinter <- divide_deaths_func(local_gedinter)

    # Track link in gedoriginal
    gedused <- local_gedinter %>%
      ungroup() %>%
      mutate(
        side_a_new_id = as.character(side_a_new_id),
        side_b_new_id = as.character(side_b_new_id),
        link_spatial_zone_wrv = 1,
        link_spatial_zone_osv = if_else(type_of_violence == 3, 1, NA_integer_),
        link_spatial_zone_nsv = if_else(type_of_violence == 2, 1, NA_integer_)
      ) %>%
      select(idsplit, side_a_new_id, side_b_new_id, final_date,
             link_spatial_zone_wrv, link_spatial_zone_osv, link_spatial_zone_nsv) %>%
      distinct(idsplit, side_a_new_id, side_b_new_id, final_date, .keep_all = TRUE)

    gedtrack <- gedtrack %>%
      left_join(
        gedused %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                           link_spatial_zone_wrv, link_spatial_zone_osv, link_spatial_zone_nsv),
        by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date")
      )

    ### wrv: Aggregate to conflict-months and add to base
    wrv <- local_gedinter %>%
      group_by(z_conf_id,final_date) %>%
      summarize(zone_wrv = sum(best),
                zone_wrv_civ = sum(deaths_civilians)) %>%
      ungroup()

    basedata$conflict_epi_id <- as.character(basedata$conflict_epi_id)
    basedata <- left_join(basedata,wrv, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        zone_wrv = if_else(missingzone == 1, NA_real_, if_else(is.na(zone_wrv), 0, zone_wrv)),
        zone_wrv_civ = if_else(missingzone == 1, NA_real_, if_else(is.na(zone_wrv_civ), 0, zone_wrv_civ))
      )

    ### osv: Aggregate to conflict-months and add to base
    osv <- local_gedinter %>% filter(type_of_violence==3) %>%
      group_by(z_conf_id,final_date) %>%
      summarize(zone_osv = sum(best)) %>%
      ungroup()

    basedata <- left_join(basedata,osv, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        zone_osv = if_else(missingzone == 1, NA_real_, if_else(is.na(zone_osv), 0, zone_osv))
      )

    ### nsv: Aggregate to conflict-months and add to base
    nsv <- local_gedinter %>% filter(type_of_violence==2) %>%
      group_by(z_conf_id,final_date) %>%
      summarize(zone_nsv = sum(best),
                zone_nsv_collciv = sum(deaths_civilians)) %>%
      ungroup()

    basedata <- left_join(basedata,nsv, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        zone_nsv = if_else(missingzone == 1, NA_real_, if_else(is.na(zone_nsv), 0, zone_nsv)),
        zone_nsv_collciv = if_else(missingzone == 1, NA_real_, if_else(is.na(zone_nsv_collciv), 0, zone_nsv_collciv))
      )

    list(basedata = basedata, gedtrack = gedtrack)

  }

  # Subfunction: govosv, confgovosv
  process_govosv <- function(divide_deaths) {
    gedinterosv <- gedintersection %>% filter(type_of_violence==3 & osv_is_gov_actor==1)

    # For confgovosv: Attach info on who the side A in z_conf_id is
    relsidea <- basedata %>% select(conflict_epi_id,month_year,side_a_id)
    gedinterosv <- left_join(gedinterosv,relsidea, by = c("z_conf_id"="conflict_epi_id","final_date"="month_year")) %>% rename(z_sidea = side_a_id)
    gedinterosv <- gedinterosv %>% mutate(confgov = if_else(side_a_new_id == z_sidea,1,0))

    # divide deaths of events that fall into several zones or not. Only zones that are "active" (exist in base) at moment of event
    baserelevantepimonths <- basedata %>% select(conflict_epi_id, month_year) %>% mutate(activeepisodes = 1)
    local_gedinter <- left_join(gedinterosv, baserelevantepimonths, by = c("z_conf_id" = "conflict_epi_id", "final_date" = "month_year"))
    local_gedinter <- local_gedinter %>% filter(activeepisodes == 1)
    if (divide_deaths) local_gedinter <- divide_deaths_func(local_gedinter)

    # Track link in gedoriginal
    gedused <- local_gedinter %>%
      ungroup() %>%
      mutate(
        side_a_new_id = as.character(side_a_new_id),
        side_b_new_id = as.character(side_b_new_id),
        link_spatial_govosv = 1,
        link_spatial_confgovosv = if_else(confgov == 1, 1, NA_integer_)
      ) %>%
      select(idsplit, side_a_new_id, side_b_new_id, final_date,
             link_spatial_govosv, link_spatial_confgovosv) %>%
      distinct(idsplit, side_a_new_id, side_b_new_id, final_date, .keep_all = TRUE)

    gedtrack <- gedtrack %>%
      left_join(
        gedused %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                           link_spatial_govosv, link_spatial_confgovosv),
        by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date")
      )


    ### Aggregate to conflict-months and add to base
    govosv <- local_gedinter %>%
      group_by(z_conf_id,final_date) %>%
      summarize(govosv = sum(best)) %>%
      ungroup()
    basedata$conflict_epi_id <- as.character(basedata$conflict_epi_id)
    basedata <- left_join(basedata,govosv, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        govosv = if_else(missingzone == 1, NA_real_, if_else(is.na(govosv), 0, govosv))
      )

    confgovosv <- local_gedinter %>% filter(confgov==1) %>%
      group_by(z_conf_id,final_date) %>%
      summarize(confgovosv = sum(best)) %>%
      ungroup()
    basedata$conflict_epi_id <- as.character(basedata$conflict_epi_id)
    basedata <- left_join(basedata,confgovosv, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        confgovosv = if_else(missingzone == 1, NA_real_, if_else(is.na(confgovosv), 0, confgovosv))
      )

    list(basedata = basedata, gedtrack = gedtrack)

  }


  # Subfunction: nsagosv
  process_nsagosv <- function(divide_deaths) {
    gedinternsv <- gedintersection %>% filter(type_of_violence==3 & osv_is_gov_actor==0)

    # I need a user choice here: divide deaths of events that fall into several zones or not. Only zones that are "active" (exist in base) at moment of event
    baserelevantepimonths <- basedata %>% select(conflict_epi_id, month_year) %>% mutate(activeepisodes = 1)
    local_gedinter <- left_join(gedinternsv, baserelevantepimonths, by = c("z_conf_id" = "conflict_epi_id", "final_date" = "month_year"))
    local_gedinter <- local_gedinter %>% filter(activeepisodes == 1)
    if (divide_deaths) local_gedinter <- divide_deaths_func(local_gedinter)

    # Track link in gedoriginal
    gedused <- local_gedinter %>%
      ungroup() %>%
      mutate(
        side_a_new_id = as.character(side_a_new_id),
        side_b_new_id = as.character(side_b_new_id),
        link_spatial_nsagosv = 1
      ) %>%
      select(idsplit, side_a_new_id, side_b_new_id, final_date,
             link_spatial_nsagosv) %>%
      distinct(idsplit, side_a_new_id, side_b_new_id, final_date, .keep_all = TRUE)

    gedtrack <- gedtrack %>%
      left_join(
        gedused %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                           link_spatial_nsagosv),
        by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date")
      )


    ### Aggregate to conflict-months and add to base
    nsagosv <- local_gedinter %>%
      group_by(z_conf_id,final_date) %>%
      summarize(nsagosv = sum(best)) %>%
      ungroup()
    basedata$conflict_epi_id <- as.character(basedata$conflict_epi_id)
    basedata <- left_join(basedata,nsagosv, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        nsagosv = if_else(missingzone == 1, NA_real_, if_else(is.na(nsagosv), 0, nsagosv))
      )

    list(basedata = basedata, gedtrack = gedtrack)

  }

  # Subfunction: internsag
  process_internsag <- function(divide_deaths) {
    gedinternsag <- gedintersection %>% filter(type_of_violence==2 & nsv_org==1)

    # I need a user choice here: divide deaths of events that fall into several zones or not. Only zones that are "active" (exist in base) at moment of event
    baserelevantepimonths <- basedata %>% select(conflict_epi_id, month_year) %>% mutate(activeepisodes = 1)
    local_gedinter <- left_join(gedinternsag, baserelevantepimonths, by = c("z_conf_id" = "conflict_epi_id", "final_date" = "month_year"))
    local_gedinter <- local_gedinter %>% filter(activeepisodes == 1)
    if (divide_deaths) local_gedinter <- divide_deaths_func(local_gedinter)

    # Track link in gedoriginal
    gedused <- local_gedinter %>%
      ungroup() %>%
      mutate(
        side_a_new_id = as.character(side_a_new_id),
        side_b_new_id = as.character(side_b_new_id),
        link_spatial_internsag = 1
      ) %>%
      select(idsplit, side_a_new_id, side_b_new_id, final_date,
             link_spatial_internsag) %>%
      distinct(idsplit, side_a_new_id, side_b_new_id, final_date, .keep_all = TRUE)

    gedtrack <- gedtrack %>%
      left_join(
        gedused %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                           link_spatial_internsag),
        by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date")
      )


    ### Aggregate to conflict-months and add to base
    internsag <- local_gedinter %>%
      group_by(z_conf_id,final_date) %>%
      summarize(internsag = sum(best),
                internsag_collciv = sum(deaths_civilians)) %>%
      ungroup()
    basedata$conflict_epi_id <- as.character(basedata$conflict_epi_id)
    basedata <- left_join(basedata,internsag, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        internsag = if_else(missingzone == 1, NA_real_, if_else(is.na(internsag), 0, internsag)),
        internsag_collciv = if_else(missingzone == 1, NA_real_, if_else(is.na(internsag_collciv), 0, internsag_collciv))
      )

    list(basedata = basedata, gedtrack = gedtrack)

  }

  # Subfunction: communal
  process_communal <- function(divide_deaths) {
    gedintercom <- gedintersection %>% filter(type_of_violence==2 & nsv_org==3)

    # I need a user choice here: divide deaths of events that fall into several zones or not. Only zones that are "active" (exist in base) at moment of event
    baserelevantepimonths <- basedata %>% select(conflict_epi_id, month_year) %>% mutate(activeepisodes = 1)
    local_gedinter <- left_join(gedintercom, baserelevantepimonths, by = c("z_conf_id" = "conflict_epi_id", "final_date" = "month_year"))
    local_gedinter <- local_gedinter %>% filter(activeepisodes == 1)
    if (divide_deaths) local_gedinter <- divide_deaths_func(local_gedinter)

    # Track link in gedoriginal
    gedused <- local_gedinter %>%
      ungroup() %>%
      mutate(
        side_a_new_id = as.character(side_a_new_id),
        side_b_new_id = as.character(side_b_new_id),
        link_spatial_communal = 1
      ) %>%
      select(idsplit, side_a_new_id, side_b_new_id, final_date,
             link_spatial_communal) %>%
      distinct(idsplit, side_a_new_id, side_b_new_id, final_date, .keep_all = TRUE)

    gedtrack <- gedtrack %>%
      left_join(
        gedused %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                           link_spatial_communal),
        by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date")
      )


    ### Aggregate to conflict-months and add to base
    communal <- local_gedinter %>%
      group_by(z_conf_id,final_date) %>%
      summarize(communal = sum(best)) %>%
      ungroup()
    basedata$conflict_epi_id <- as.character(basedata$conflict_epi_id)
    basedata <- left_join(basedata,communal, by = c("conflict_epi_id"="z_conf_id", "month_year"="final_date"))
    basedata <- basedata %>%
      mutate(
        communal = if_else(missingzone == 1, NA_real_, if_else(is.na(communal), 0, communal))
      )

    list(basedata = basedata, gedtrack = gedtrack)

  }

  # Wrap it all up

  # Step 1: Process zone_wrv, osv, and nsv
  result_wrv <- process_wrv(divide_deaths)
  basedata <- left_join(basedata, result_wrv$basedata %>% select(conflict_epi_id, month_year, zone_wrv, zone_wrv_civ, zone_osv, zone_nsv, zone_nsv_collciv),
                    by = c("conflict_epi_id", "month_year"))
  gedtrack <- left_join(gedtrack, result_wrv$gedtrack %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                                                                          link_spatial_zone_wrv, link_spatial_zone_osv, link_spatial_zone_nsv),
                           by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date"))

  # Step 2: Process govosv and confgovosv
  result_govosv <- process_govosv(divide_deaths)
  basedata <- left_join(basedata, result_govosv$basedata %>% select(conflict_epi_id, month_year, govosv, confgovosv),
                    by = c("conflict_epi_id", "month_year"))
  gedtrack <- left_join(gedtrack, result_govosv$gedtrack %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                                                                             link_spatial_govosv, link_spatial_confgovosv),
                           by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date"))

  # Step 3: Process nsagosv
  result_nsagosv <- process_nsagosv(divide_deaths)
  basedata <- left_join(basedata, result_nsagosv$basedata %>% select(conflict_epi_id, month_year, nsagosv),
                    by = c("conflict_epi_id", "month_year"))
  gedtrack <- left_join(gedtrack, result_nsagosv$gedtrack %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                                                                              link_spatial_nsagosv),
                           by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date"))

  # Step 4: Process internsag
  result_internsag <- process_internsag(divide_deaths)
  basedata <- left_join(basedata, result_internsag$basedata %>% select(conflict_epi_id, month_year, internsag, internsag_collciv),
                    by = c("conflict_epi_id", "month_year"))
  gedtrack <- left_join(gedtrack, result_internsag$gedtrack %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                                                                                link_spatial_internsag),
                           by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date"))

  # Step 5: Process communal violence
  result_communal <- process_communal(divide_deaths)
  basedata <- left_join(basedata, result_communal$basedata %>% select(conflict_epi_id, month_year, communal),
                    by = c("conflict_epi_id", "month_year"))
  gedtrack <- left_join(gedtrack, result_communal$gedtrack %>% select(idsplit, side_a_new_id, side_b_new_id, final_date,
                                                                               link_spatial_communal),
                           by = c("idsplit", "side_a_new_id", "side_b_new_id", "final_date"))

  # Save the final datasets
  return(list(basedata = basedata, gedtrack = gedtrack))

}
